# Generated by Django 4.0.1 on 2022-01-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_customuser_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_no',
        ),
    ]
