# Generated by Django 4.0.1 on 2022-01-28 07:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='events/images')),
                ('categories', models.CharField(choices=[('UG', 'Under-Graduate'), ('PG', 'Post-Graduate'), ('DS', 'Doctoralstudies'), ('VE', 'Vocational Education'), ('DE', 'Distance Education')], default='UG', max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
