# Generated by Django 3.2.11 on 2022-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.CharField(choices=[('Under-Graduate', 'Under-Graduate'), ('Post-Graduate', 'Post-Graduate'), ('Doctoralstudies', 'Doctoralstudies'), ('Vocational Education', 'Vocational Education'), ('istance Education', 'Distance Education')], default='UG', max_length=100),
        ),
    ]
