# Generated by Django 3.2.11 on 2022-02-03 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='event_disliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
