# Generated by Django 3.2.11 on 2022-02-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_event_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
